# -*- coding: utf-8 -*-
"""690_Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nOnxqlbW-AynJfoM9A81jQVJQI-z_NYH

# Assignment 02

#### Prompts a user to enter 10 integers. If the user enters anything other than integers, remind her that only integers are allowed and let her retry. Don't allow the user to enter more than 10 or less than 10 integers. Display the 10 integers back to the user at the end. Calculate the following statistics from the 10 integers entered:

* Minimum
* Maximum
* Range
* Mean
* Variance
* Standard Deviation

#### User_Input Function
* User_Input function reads the input from the user. According to the given statement user need to enter 10 integer values seperated by a space so that it will be easy to understand the values that are entered.
* map function syntax map(function, iterator)
* map here the integer function is applied to all the values that are entered
"""

# Read input from the user
def User_Input():
  return list(map(int,input("Please enter 10 integers seperated by a spaces\n").split()))
#User_Input()

"""#### Min() Function:
* Min() function calculates the minimum value of all the 10 elements and returns the value that is called in the main function to display the minimum value.
"""

def Min(numbers):
  min = numbers[0] # first element is assigned to min
  for i in numbers: 
      if i < min:  #checking if any element is less than the min
          min = i   # changing the value to min
  return min
#Min()

"""#### Max() Function:
* Max() function calculates the maximum value of all the 10 elements and returns the value. 
* This function is called in the main function to display the maximum value.
"""

def Max(numbers):
  max = numbers[0] # first element is assigned to max
  for i in numbers: 
      if i > max:  #checking if any element is greater than the max
          max = i  # changing the value to max
  return max
#Max()

"""#### Range() Function:
* In general range is defined as the difference between the maximum and the minimum value so this function calculates the range by calling the two functions Min(),Max() and the difference is returned as range which is called to display the Range in the main function.
"""

def Range(numbers):
  range = Max(numbers)-Min(numbers)
  return range
#Range()

"""#### Mean() Function:
* This function returns mean of the elements and it is the sum of all the elements divided by the total number of elements. 
* The Mean() is called in the main function to display the Mean() of elements
"""

def Mean(numbers):
  sum = 0
  for i in numbers:
    sum+=i

  mean = sum/10
  return mean
#Mean()

"""Varience() Function:
This function returns the varience and it is calculated as:
* summation of the elements after the subtraction of the individual element from the mean of elements and then squared the result
* This function is called to display the Varience in the main function
"""

def Varience(numbers):
  n=10
  sum2=0
  for i in numbers:
      sum2 = sum2 + (i-mean())**2

  var = sum2/n
  return var
#Varience()

"""#### Standard_Deviation Function():
* This function returns the standard deviation of elements and it is simply defined as the square root of the varience.
* This function is called to display the Standard deviation in the main function
"""

import math
def Standard_Deviation(numbers):
  std = Varience(numbers)**0.5
  return std
#Standard_Deviation()

"""Main() Function:
* This function takes input from User_Input and checks if the entered integers meets the requirements and displays the respective message.
* It dispalys the entered values if the all the requirements are met.
* This function takes the inputs from Min(), Max(), Range(), Mean(), Varience, Standard Deviation() and displays them upon calling.
"""

# Function block to check the count and if the number is an integer or not.
def main():
  n = 10
  try:
    list_of_numbers =  User_Input()
    #print(list_of_numbers)
  except:
    print("Please enter integer values only\n")
    list_of_numbers = User_Input()
  if len(list_of_numbers)!=10:
    print("Please enter 10 integers only")
  else: 
    print("Printing the elements that are entered\n")
    for i in list_of_numbers:
      print(i,end=" ")
    print("\n")
    print("Minimum Value: ",str(Min(list_of_numbers))+"\n")
    print("Maximum Value: ",str(Max(list_of_numbers))+"\n")
    print("Range: ",str(Range(list_of_numbers))+"\n")
    print("Mean: ",str(Mean(list_of_numbers))+"\n")
    print("Varience: ",str(Varience(list_of_numbers))+"\n")
    print("Standard Deviation: ",str(Standard_Deviation(list_of_numbers))+"\n")

main()